apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

nameSuffix: -prod

replicas:
  - name: aureus-console
    count: 3

resources:
  - ingress.yaml
  - hpa.yaml
  - network-policy.yaml

configMapGenerator:
  - name: aureus-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - LLM_MOCK_FALLBACK=false
      - DATABASE_SSL=true

images:
  - name: aureus/console
    newTag: v1.0.0  # Use specific version in production
